CC        := gcc
DATADIR   := data
SRCDIR    := src
BUILDDIR  := build
TARGETDIR := bin
TARGET    := $(TARGETDIR)/otw
SOURCES   := $(shell find $(SRCDIR) -type f -name "*.c")
OBJECTS   := $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.c=.o))
DATA      := $(shell find $(DATADIR) -type f -name "*.dat")
CFLAGS    := -Wall -Wextra -pedantic -Werror -g -save-temps
INC       := -Iinclude
LIBS      := -lssh2

$(TARGET): $(OBJECTS)
	@echo "[+] Building target executable..."
	@mkdir -p $(DATADIR)
	@mkdir -p $(TARGETDIR)
	@echo "$(CC) $(CFLAGS) $^ -o $(TARGET) $(LIBS)"; $(CC) $(CFLAGS) $^ -o $(TARGET) $(LIBS)

$(BUILDDIR)/%.o: $(SRCDIR)/%.c
	@echo "[+] Building intermediates..."
	@mkdir -p $(BUILDDIR)
	@echo "$(CC) $(CFLAGS) $(INC) -c -o $@ $<"; $(CC) $(CFLAGS) $(INC) -c -o $@ $<

.PHONY: clean
clean:
	@echo "Cleaning up..."
	@echo "$(RM) -r $(BUILDDIR) $(TARGETDIR) $(DATA)"; $(RM) -r $(BUILDDIR) $(TARGETDIR) $(DATA)
